name = "truco-club"
main = "src/index.js"
compatibility_date = "2024-09-28"
workers_dev = true

routes = [
  { pattern = "*clubtruco.com/*", zone_id = "bcec68d3c11a2e3c3a8441e8a6387bc8" }
]

[assets]
directory = "."
binding = "ASSETS"

[[kv_namespaces]]
binding = "TRUCO_KV"
id = "888849ef1c8a40288999c64520c24cbd"



